export const RUNES = [
  { id: 'fehu',     unicodeSymbol: 'ᚠ', isReversible: true  },
  { id: 'uruz',     unicodeSymbol: 'ᚢ', isReversible: true  },
  { id: 'thurisaz', unicodeSymbol: 'ᚦ', isReversible: true  },
  { id: 'ansuz',    unicodeSymbol: 'ᚨ', isReversible: true  },
  { id: 'raidho',   unicodeSymbol: 'ᚱ', isReversible: true  },
  { id: 'kenaz',    unicodeSymbol: 'ᚲ', isReversible: true  },
  { id: 'gebo',     unicodeSymbol: 'ᚷ', isReversible: false },
  { id: 'wunjo',    unicodeSymbol: 'ᚹ', isReversible: true  },
  { id: 'hagalaz',  unicodeSymbol: 'ᚺ', isReversible: false },
  { id: 'nauthiz',  unicodeSymbol: 'ᚾ', isReversible: true  },
  { id: 'isa',      unicodeSymbol: 'ᛁ', isReversible: false },
  { id: 'jera',     unicodeSymbol: 'ᛃ', isReversible: false },
  { id: 'eihwaz',   unicodeSymbol: 'ᛇ', isReversible: false },
  { id: 'perthro',  unicodeSymbol: 'ᛈ', isReversible: true  },
  { id: 'algiz',    unicodeSymbol: 'ᛉ', isReversible: true  },
  { id: 'sowilo',   unicodeSymbol: 'ᛊ', isReversible: false },
  { id: 'tiwaz',    unicodeSymbol: 'ᛏ', isReversible: true  },
  { id: 'berkano',  unicodeSymbol: 'ᛒ', isReversible: true  },
  { id: 'ehwaz',    unicodeSymbol: 'ᛖ', isReversible: true  },
  { id: 'mannaz',   unicodeSymbol: 'ᛗ', isReversible: true  },
  { id: 'laguz',    unicodeSymbol: 'ᛚ', isReversible: true  },
  { id: 'ingwaz',   unicodeSymbol: 'ᛜ', isReversible: false },
  { id: 'dagaz',    unicodeSymbol: 'ᛞ', isReversible: false },
  { id: 'othala',   unicodeSymbol: 'ᛟ', isReversible: false },
  { id: 'blank',    unicodeSymbol: '◻', isReversible: false },
];
