export interface Rune {
  id: string;
  name: string;
  unicodeSymbol: string;
  keywords: string[];
  isReversible: boolean;
  uprightMeaning: string;
  reversedMeaning?: string;
}

export const RUNES: Rune[] = [
  {
    id: 'fehu',
    name: 'Fehu',
    unicodeSymbol: 'ᚠ',
    keywords: ['abundance', 'wealth', 'fertility', 'new beginnings'],
    isReversible: true,
    uprightMeaning: `Fehu speaks of cattle — the ancient measure of wealth — and carries the energy of abundance in motion. This is not idle gold locked in a vault, but living, breathing prosperity that grows, multiplies, and flows. When Fehu appears, resources are available to you: financial opportunity, creative energy, or the raw material from which something new can be built. It asks you to receive without shame and to steward what comes with care. Wealth gathered and never shared stagnates; wealth circulated returns enriched. Consider where in your life abundance is trying to reach you, and whether you are open to receiving it. Fehu also marks fertile beginnings — a new venture, a new relationship, a new phase of life. The energy is generative. Act while the soil is warm.`,
    reversedMeaning: `Reversed, Fehu signals a loss or blockage in the flow of resources. Something you counted on may not arrive, or what you have may be slipping away. This is not catastrophe — it is a call to examine how you relate to material security. Are you grasping too tightly, or spending without replenishment? There may be an imbalance: giving more than you receive, or taking more than you give. Fehu reversed also cautions against starting new ventures now — the ground is not ready. Focus on conservation, on repairing what is broken, and on understanding why the flow has stopped before trying to force it open again.`,
  },
  {
    id: 'uruz',
    name: 'Uruz',
    unicodeSymbol: 'ᚢ',
    keywords: ['strength', 'vitality', 'endurance', 'health'],
    isReversible: true,
    uprightMeaning: `Uruz is the wild ox — immense, untamed, and full of vital force. This rune carries the energy of raw physical and inner strength, the kind that does not ask permission and does not negotiate with weakness. When Uruz appears, something powerful is moving in your life or within you. A period of difficulty may be ending, replaced by a surge of health, confidence, or momentum. Your body may be asking for more activity, more challenge; your spirit may be ready to take on something that once seemed too large. Uruz does not guarantee smooth passage — the wild ox does not walk carefully — but it promises the strength to push through. Trust your instincts. Move boldly. You are more capable than you have allowed yourself to believe.`,
    reversedMeaning: `When Uruz falls reversed, the great strength is present but misdirected, blocked, or wasting away from disuse. You may be forcing things that need to be released, or neglecting a body or spirit that is crying out for care. There is a risk of burnout from pushing too hard, or conversely, stagnation from not pushing enough. Reversed Uruz can also signal a period of physical vulnerability — pay attention to your health, rest when rest is needed, and do not mistake stubbornness for strength. The ox that charges a stone wall breaks itself. Know when to charge and when to wait for the gate to open.`,
  },
  {
    id: 'thurisaz',
    name: 'Thurisaz',
    unicodeSymbol: 'ᚦ',
    keywords: ['protection', 'threshold', 'conflict', 'defense'],
    isReversible: true,
    uprightMeaning: `Thurisaz is the thorn — the gate-guardian, the force that both wounds and protects. It marks a threshold between what was and what is to come. This rune is not comfortable; it does not smooth over difficulty. Instead, it places you at the edge of something that demands a choice. A conflict may be unavoidable, a confrontation necessary, an old pattern requiring a decisive break. Thurisaz can also appear as protection — a warning to pause before crossing a boundary, or a shield against forces that mean you harm. If you are about to make a major decision, this rune counsels: look carefully before you step through. Not everything waiting on the other side is as it appears. The thorn guards the rose.`,
    reversedMeaning: `Reversed, Thurisaz warns of danger overlooked, or of defenses that have become weapons turned inward. You may be your own worst enemy right now — attacking yourself, your relationships, or your opportunities with a ferocity that serves no one. There may also be a tendency to ignore warning signs, to push through a boundary that is there for good reason. Conflict that is forced rather than necessary leaves wounds that take long to heal. Reversed Thurisaz asks: what are you protecting, and who are you actually protecting it from?`,
  },
  {
    id: 'ansuz',
    name: 'Ansuz',
    unicodeSymbol: 'ᚨ',
    keywords: ['communication', 'wisdom', 'signals', 'messages'],
    isReversible: true,
    uprightMeaning: `Ansuz carries the breath of Odin — the divine word, the message, the signal. This rune is about communication in its deepest sense: not just speaking, but listening. Something is trying to reach you. A conversation may carry more meaning than its surface words suggest; a dream, a repeated encounter, a feeling in the gut — these are channels. Ansuz calls you to pay attention, to listen with more than your ears. It also governs your own voice: this is a favorable time to speak truth, to write, to teach, or to reach out to someone you have been putting off. Clarity is available. The transmission is clear if you tune in.`,
    reversedMeaning: `Reversed Ansuz points to disrupted communication — crossed signals, deception, or a message that is being blocked, distorted, or ignored. You may be speaking but not being heard, or hearing but not truly listening. There may also be self-deception at work: a story you tell yourself that no longer matches reality. Watch for miscommunication in important conversations. Ask for clarification. Do not assume you understood or that you were understood. There may be someone in your environment who is not speaking honestly with you.`,
  },
  {
    id: 'raidho',
    name: 'Raidho',
    unicodeSymbol: 'ᚱ',
    keywords: ['journey', 'movement', 'right action', 'rhythm'],
    isReversible: true,
    uprightMeaning: `Raidho is the wheel — the journey, both literal and inner. It speaks of movement that is purposeful and aligned, of being in the right place at the right time because you are moving with the rhythm of your own life rather than against it. If travel is on your horizon, Raidho blesses it. If you are navigating a long project or process, this rune signals that you are on track and the path ahead is open. It is also a rune of right action — doing the thing that must be done, in the right order, at the right time. There is a natural rhythm to events, and Raidho invites you to find it rather than forcing your own tempo.`,
    reversedMeaning: `Reversed, Raidho signals disruption in the journey — a delay, a detour, or a sense that you are moving but going nowhere. Plans may be disrupted by external forces, or you may be moving out of alignment with your deeper purpose. Physical travel may face obstacles. More broadly, this rune reversed asks you to examine whether the direction you are heading is truly the right one. It is better to pause and recalibrate than to arrive somewhere you never wanted to be.`,
  },
  {
    id: 'kenaz',
    name: 'Kenaz',
    unicodeSymbol: 'ᚲ',
    keywords: ['clarity', 'creativity', 'illumination', 'craft'],
    isReversible: true,
    uprightMeaning: `Kenaz is the torch held aloft in the dark — the creative fire, the craft well practiced, the moment when confusion gives way to clarity. This rune marks a time of illumination. Something that was murky is becoming clear; something you have been trying to create is finding its form. Kenaz favors all creative work — writing, building, designing, problem-solving — and encourages you to bring your full attention and skill to whatever you are making. It is also the fire of intimacy: the warm light shared between people who genuinely see one another. The torch of Kenaz is meant to illuminate, not to consume. Use your fire with intention.`,
    reversedMeaning: `Reversed, Kenaz signals a loss of clarity or creative fire. The torch flickers or goes dark. You may be feeling uninspired, confused, or creatively blocked. The light you relied on to guide you may be failing. This is a time for rest rather than forcing output — you cannot fuel a fire that has no fuel. Alternatively, reversed Kenaz can point to deception coming to light: something hidden is about to be revealed, and not necessarily something you wanted seen. Look honestly at what the light shows you.`,
  },
  {
    id: 'gebo',
    name: 'Gebo',
    unicodeSymbol: 'ᚷ',
    keywords: ['gift', 'exchange', 'generosity', 'partnership'],
    isReversible: false,
    uprightMeaning: `Gebo is the mark of the gift — and in the old Norse understanding, a gift always creates a bond. This rune speaks of exchange in its most balanced form: giving and receiving held in equal measure. It may mark the arrival of a genuine gift, an opportunity, or a partnership that is rooted in mutual respect and fair exchange. Gebo honors connection — between people, between the human and the sacred, between the effort you give and the return that comes. It is also a reminder that receiving is not weakness; to refuse a gift graciously offered is to break the circuit of generosity. Where in your life is a genuine exchange of value happening? Honor it. Gebo does not reverse — the gift, once given, changes everything.`,
  },
  {
    id: 'wunjo',
    name: 'Wunjo',
    unicodeSymbol: 'ᚹ',
    keywords: ['joy', 'harmony', 'belonging', 'fulfillment'],
    isReversible: true,
    uprightMeaning: `Wunjo is joy — the deep, settled kind that comes not from excitement but from being exactly where you belong. This rune marks a time of harmony, of things coming together in a way that feels right and earned. The conflict that has been grinding you down may ease; a relationship may deepen into genuine warmth; a long effort may finally show its fruit. Wunjo is also the joy of community, of being part of something larger than yourself, of shared purpose and belonging. Do not dismiss this moment. Happiness, when it arrives, deserves to be fully inhabited. Let yourself be content.`,
    reversedMeaning: `Reversed, Wunjo signals a disturbance in the harmony — joy deferred, belonging denied, or contentment soured by unresolved tension. You may be surrounded by the conditions for happiness but unable to feel it, perhaps because of grief, resentment, or anxiety that has not yet been addressed. Alternatively, you may be chasing a version of happiness that is not authentic to who you actually are. Reversed Wunjo asks: what is standing between you and genuine peace? The answer may be uncomfortable, but it is the path through.`,
  },
  {
    id: 'hagalaz',
    name: 'Hagalaz',
    unicodeSymbol: 'ᚺ',
    keywords: ['disruption', 'hail', 'transformation', 'crisis'],
    isReversible: false,
    uprightMeaning: `Hagalaz is hail — sudden, destructive, and utterly impersonal. This rune does not negotiate and does not warn you twice. It marks the arrival of a disruption that is outside your control: circumstances shifting forcefully, plans upended, something broken that you cannot fix by will alone. The hailstorm does not hate the crop it damages; it simply falls. What matters is what you do in the aftermath. Hagalaz, though harsh, carries within it the seed of transformation — the old must sometimes be shattered for the new to emerge. Do not try to stop what is already in motion. Seek shelter, wait out the storm, and begin again when the ground is clear. Hagalaz does not reverse; what falls, falls.`,
  },
  {
    id: 'nauthiz',
    name: 'Nauthiz',
    unicodeSymbol: 'ᚾ',
    keywords: ['need', 'constraint', 'patience', 'necessity'],
    isReversible: true,
    uprightMeaning: `Nauthiz is the need-fire — the friction that produces flame. It speaks of constraint, limitation, and the very real experience of not having enough: not enough time, resources, freedom, or support. But Nauthiz is not merely about suffering — it is about what necessity teaches. Constraint is a forge. The things you build under limitation are often stronger than the things built in abundance, because scarcity demands ingenuity and patience. If you are struggling, do not look away from the struggle. Look at what it is teaching you. There is also a warning here: do not act impulsively from a place of need. Desperation drives poor decisions. Slow down. The fire is inside you already.`,
    reversedMeaning: `Reversed Nauthiz intensifies the sense of constraint without offering the silver lining of growth. The limitation is not teaching you anything useful right now — it is simply draining you. You may be trapped in a situation or pattern that is serving no one, least of all yourself. There may be stubbornness at play: refusing to admit need, refusing to ask for help, insisting on going it alone past the point of wisdom. Reversed Nauthiz asks: what are you not allowing yourself to receive?`,
  },
  {
    id: 'isa',
    name: 'Isa',
    unicodeSymbol: 'ᛁ',
    keywords: ['stillness', 'pause', 'ice', 'clarity'],
    isReversible: false,
    uprightMeaning: `Isa is ice — still, silent, and crystalline. The river has stopped flowing, and nothing is moving forward right now. This is not failure; it is winter. Isa asks you to stop pushing, stop forcing, and simply be still. There is wisdom in the pause that cannot be found in motion. The ice preserves as well as halts; what is frozen is also held. If your plans are stalled, your relationships feel cold, or your creative well has run dry — welcome the stillness rather than fighting it. Use this time for reflection, for inner work, for examining what you actually want once the thaw comes. Ice does not reverse; the stillness is what it is.`,
  },
  {
    id: 'jera',
    name: 'Jera',
    unicodeSymbol: 'ᛃ',
    keywords: ['harvest', 'cycle', 'patience', 'reward'],
    isReversible: false,
    uprightMeaning: `Jera is the year — the full cycle from planting to harvest. This rune speaks of natural timing, of the understanding that good things do not arrive out of season. If you have been working steadily toward something, Jera is a deeply welcome sign: the harvest is coming. The effort you have put in — the long hours, the careful tending, the patience when results were invisible — is about to bear fruit. This is not luck. It is consequence. At the same time, Jera reminds you that the cycle does not end at harvest: the field must rest, the seeds must be saved, the next planting must be planned. Celebrate what is coming, then turn your mind to what comes after. Jera does not reverse; cycles do not pause for impatience.`,
  },
  {
    id: 'eihwaz',
    name: 'Eihwaz',
    unicodeSymbol: 'ᛇ',
    keywords: ['endurance', 'depth', 'the axis', 'resilience'],
    isReversible: false,
    uprightMeaning: `Eihwaz is the yew — the tree that lives for millennia, that bends without breaking, that reaches simultaneously into earth and sky. This rune speaks of endurance rooted in depth: the ability to withstand what would break lesser things, not through hardness, but through flexibility and deep rootedness. Eihwaz appears when you are being tested in ways that feel like too much — and it says: you are more resilient than you know. It also marks the axis between worlds, the liminal space where transformation happens. Something in you is changing at a fundamental level. This process cannot be hurried. Go deep into your roots and hold on. Eihwaz does not reverse; the yew stands.`,
  },
  {
    id: 'perthro',
    name: 'Perthro',
    unicodeSymbol: 'ᛈ',
    keywords: ['mystery', 'chance', 'hidden knowledge', 'fate'],
    isReversible: true,
    uprightMeaning: `Perthro is the dice cup — upturned, concealing its contents until the moment of reveal. This is the rune of mystery, of the unknown, of the things that are happening beneath the surface of visible events. Something is in play that you cannot yet see or fully understand, and Perthro counsels you to make peace with that uncertainty. There is also an invitation here to explore: to go deeper into your own hidden landscape, to examine what you have kept secret even from yourself. Mystery is not the enemy of understanding — it is the doorway. What is still concealed may be the most important thing about the situation.`,
    reversedMeaning: `Reversed, Perthro suggests that what is hidden is staying hidden — perhaps by your own refusal to look, or by forces actively keeping information from you. Secrets may be working against you. There may also be a pattern of magical thinking or wishful fantasy in play: hoping that chance will save you from a situation that requires direct action. The dice cannot be wished to land a certain way. If you need information, go get it. If you are avoiding something because you fear what you will find, that avoidance is costing you.`,
  },
  {
    id: 'algiz',
    name: 'Algiz',
    unicodeSymbol: 'ᛉ',
    keywords: ['protection', 'sanctuary', 'guardian', 'instinct'],
    isReversible: true,
    uprightMeaning: `Algiz is the elk-sedge — a plant with razor edges that cuts anyone who grabs it carelessly, protecting the marshy ground it grows in. This rune speaks of protection, both given and received. Your instincts are sharp right now; trust them. If something feels wrong, it probably is. If someone or something feels safe, that intuition is worth honoring. Algiz also marks a time when guardianship and mentorship are relevant — either you are in a position to protect or guide someone else, or you need to seek out someone who can offer you that shelter. There is a sanctuary available to you. You do not have to face this alone.`,
    reversedMeaning: `Reversed, Algiz signals that the protection is weakened. You may be vulnerable in ways you have not acknowledged — perhaps running on empty, ignoring your instincts, or trusting someone or something that cannot actually hold you safe. There may also be a pattern of compulsive caretaking: sacrificing your own wellbeing to protect others, until you have nothing left to give. Reversed Algiz asks you to check your own defenses. Is your armor on? Are you rested enough, resourced enough, clear enough to handle what is in front of you?`,
  },
  {
    id: 'sowilo',
    name: 'Sowilo',
    unicodeSymbol: 'ᛊ',
    keywords: ['sun', 'success', 'vitality', 'wholeness'],
    isReversible: false,
    uprightMeaning: `Sowilo is the sun — the force of clarity, vitality, and will that cannot be stopped. This rune is pure directional energy: pointing toward success, toward health, toward the realization of what you have been working for. When Sowilo appears, the light is on your side. A goal you have been pursuing may be closer than it appears; a health concern may be turning a corner; a sense of purpose and personal power may be returning after a period of shadow. Sowilo also marks the moment when you understand yourself more clearly — when the fog lifts and you can see who you actually are and what you are actually for. Claim your light. Sowilo does not reverse; the sun rises.`,
  },
  {
    id: 'tiwaz',
    name: 'Tiwaz',
    unicodeSymbol: 'ᛏ',
    keywords: ['justice', 'sacrifice', 'honor', 'victory'],
    isReversible: true,
    uprightMeaning: `Tiwaz is Tyr's rune — the sky god who sacrificed his hand to bind the great wolf, for the good of all. This rune speaks of justice, of doing what is right even when the personal cost is real. There is a battle or conflict ahead, or perhaps already underway, and Tiwaz says: fight for what is true and right, not merely for what benefits you. Honor matters. Integrity matters. The outcome of this situation will be shaped by whether all parties — but especially you — act with honesty and fairness. Tiwaz also marks the warrior spirit: courage, discipline, and the willingness to make necessary sacrifices. Victory is possible, but it must be earned rightly.`,
    reversedMeaning: `Reversed Tiwaz signals a corruption of justice — unfairness, abuse of authority, or a sacrifice made for the wrong reasons. There may be a legal or ethical conflict in which the outcome is unjust. There may also be a loss of courage: backing down from a necessary confrontation, or compromising your integrity because the fight seems too costly. Reversed Tiwaz asks: what are you unwilling to sacrifice that you should be? And conversely: is there a sacrifice being demanded of you that is actually unjust? Not all demands for selflessness are righteous.`,
  },
  {
    id: 'berkano',
    name: 'Berkano',
    unicodeSymbol: 'ᛒ',
    keywords: ['birth', 'nurturing', 'growth', 'new life'],
    isReversible: true,
    uprightMeaning: `Berkano is the birch — one of the first trees to return after the long winter, full of the vitality of new growth. This rune governs birth in all its forms: the birth of a child, a project, a relationship, a creative work, a new phase of life. It is also the rune of nurturing — the patient, sustained care that turns a seed into a living thing. Something new is beginning in your life, and it needs your attention, warmth, and protection. This is not the time for grand gestures; it is the time for consistent, gentle tending. Whatever you are growing, it is alive. Feed it well.`,
    reversedMeaning: `Reversed, Berkano signals that something which should be growing is being neglected or smothered. Either you are not giving enough care and attention to what is new in your life, or you are caring in a way that stifles rather than nurtures — overprotection, control, refusing to allow natural development. There may also be a literal concern about fertility, physical health, or the health of a project at an early stage. Ask honestly: is what I am nurturing getting what it actually needs from me?`,
  },
  {
    id: 'ehwaz',
    name: 'Ehwaz',
    unicodeSymbol: 'ᛖ',
    keywords: ['partnership', 'movement', 'trust', 'cooperation'],
    isReversible: true,
    uprightMeaning: `Ehwaz is the horse — and specifically the relationship between horse and rider, built on trust, communication, and mutual respect. Neither dominates; both must cooperate for the journey to succeed. This rune speaks of partnership in all its forms: a business collaboration, a marriage, a friendship, a working team. The relationship at the center of your question is one where true cooperation is possible — or necessary. Ehwaz also signals movement and travel: things are progressing, shifting, and there is an energy of momentum available if you work with those around you rather than against them. Trust the partnership. The horse knows the terrain.`,
    reversedMeaning: `Reversed, Ehwaz signals disharmony in partnership — a collaboration that has lost its trust, or a situation where one party is carrying more than their share. There may be a power imbalance, miscommunication, or a fundamental difference in direction that has not yet been named. Travel or movement may be disrupted. Reversed Ehwaz asks: is this partnership truly mutual? Is there honesty between you and whoever you are working alongside? If the horse and rider are fighting each other, neither will arrive.`,
  },
  {
    id: 'mannaz',
    name: 'Mannaz',
    unicodeSymbol: 'ᛗ',
    keywords: ['humanity', 'self', 'community', 'the mind'],
    isReversible: true,
    uprightMeaning: `Mannaz is the human — both the self and the community, the individual and the collective. This rune asks you to consider yourself honestly: not with pride or shame, but with clear-eyed recognition of what you are — capable, fallible, connected, and distinct. It is also the rune of the social world: your place within your community, the roles you play, how you are perceived and how you perceive others. At its best, Mannaz points to a moment of genuine self-knowledge and social harmony. You understand yourself a little better than you did before. You see those around you more clearly. This understanding is the foundation for right action.`,
    reversedMeaning: `Reversed, Mannaz signals a distortion in how you see yourself or how you relate to others. There may be excessive self-criticism or, conversely, blind pride. You may be isolated, disconnected from community, or entangled in social dynamics that are draining you. There may also be an enemy or rival influencing your situation — someone working against your interests. Reversed Mannaz asks: who do you actually see when you look in the mirror? And who do the people around you actually see?`,
  },
  {
    id: 'laguz',
    name: 'Laguz',
    unicodeSymbol: 'ᛚ',
    keywords: ['water', 'intuition', 'flow', 'the unconscious'],
    isReversible: true,
    uprightMeaning: `Laguz is water — the lake, the river, the deep well. It speaks of intuition, of the emotional body, of everything that moves beneath the rational surface. If you have been relying too heavily on logic and planning, Laguz invites you to go under the surface and feel your way forward. Your gut knows things your mind has not yet articulated. Dreams may be particularly informative right now. There is also an element of flow: stop fighting the current and let the water carry you. The path of least resistance is not always the path of laziness — sometimes it is the path of wisdom.`,
    reversedMeaning: `Reversed, Laguz signals that you are at risk of being overwhelmed by emotion — swept away by fear, grief, obsession, or longing that has not been grounded. You may be making decisions from a reactive or avoidant emotional state rather than from centered feeling. Alternatively, you may be blocking your own intuition, trying to think your way through something that requires feeling. The waters are churned and murky. Slow down before you act. Let the sediment settle.`,
  },
  {
    id: 'ingwaz',
    name: 'Ingwaz',
    unicodeSymbol: 'ᛜ',
    keywords: ['completion', 'gestation', 'inner work', 'readiness'],
    isReversible: false,
    uprightMeaning: `Ingwaz is the seed in the ground — full of potential, complete in itself, waiting for the right moment to emerge. This rune speaks of an inner completion: something within you has reached a point of readiness, of wholeness that does not yet need to be shown to the world. You may be in a period of deep inner work, of gestation, of gathering your forces before a significant emergence. This is not inaction — it is preparation. The seed does not need to explain itself while it is germinating. Trust the process. The breakthrough, when it comes, will not need to be announced. It will simply be visible. Ingwaz does not reverse; what is complete is complete.`,
  },
  {
    id: 'dagaz',
    name: 'Dagaz',
    unicodeSymbol: 'ᛞ',
    keywords: ['dawn', 'breakthrough', 'transformation', 'clarity'],
    isReversible: false,
    uprightMeaning: `Dagaz is the dawn — the moment when darkness gives way to light, when what was hidden becomes suddenly, irreversibly visible. This rune marks a breakthrough: a shift so significant that things cannot go back to the way they were. It may be an insight that changes how you see everything, a moment of genuine transformation, a door opening onto a fundamentally different chapter of life. Dagaz is not subtle. When this rune appears, something is changing at the root. Welcome it. The dawn does not care whether you are ready — it comes regardless. What it offers is clarity, and clarity, even when it is uncomfortable, is always a gift. Dagaz does not reverse; the dawn always follows the dark.`,
  },
  {
    id: 'othala',
    name: 'Othala',
    unicodeSymbol: 'ᛟ',
    keywords: ['heritage', 'home', 'inheritance', 'belonging'],
    isReversible: false,
    uprightMeaning: `Othala is the ancestral enclosure — the home place, the inherited land, the legacy that comes before and after you. This rune speaks of what you carry from your lineage: the gifts, the patterns, the wounds, the wisdom. It also speaks of home in the fullest sense — not just a building, but a sense of belonging and rootedness that makes you who you are. There may be family matters on your horizon that deserve attention. There may also be gifts of tradition — skills, knowledge, or perspectives passed down — that are available to you right now if you claim them. What do you carry that is truly yours? What have you inherited that serves you? Othala does not reverse; what is inherited is inherited.`,
  },
  {
    id: 'blank',
    name: 'Odin (Blank Rune)',
    unicodeSymbol: '◻',
    keywords: ['the unknown', 'fate', 'surrender', 'the void'],
    isReversible: false,
    uprightMeaning: `The Blank Rune is Odin's rune — the rune of the unknowable, of the moment before form, of the question that has no answer yet. Some traditions do not include it in the Elder Futhark set, and its presence here is itself a kind of statement: not everything can be read. When you draw the Blank Rune, you are invited to sit with uncertainty. The universe is not withholding information from you to be cruel — it is asking you to trust the unfolding without needing to know how it ends. This is perhaps the most difficult rune to receive, and perhaps the most honest. There is a great freedom in accepting that you do not know. Release the need to control the outcome. Be present. The answer will come, in its own form, in its own time.`,
  },
];
